### PR TITLE
updated to the new LAGER_STRUCT

### PR DESCRIPTION
**Pull request by cyrilRomain**
Needed to build ewig with a >= 2022 lager master. 

BTW I noticed lager version is 0.0.0. Although there is no versioned release (yet), bumping the version, especially on breaking change, still helps to refer to a version in use, and to make commit message more clear (ex: "bump to lager 0.1.0").

### CODE REVIEW

**Comment by arximboldi** [comment]
The build failed because it needs to be updated here, so `nix-build` works: https://github.com/arximboldi/ewig/blob/master/nix/deps.nix

Now that we are at it we could also update Immer, which has had a few improvements since :smile:

**Comment by cyrilRomain** [comment]
Indeed thanks.
Found how to generate sha256 commit hash with nix-prefetch.
Commit updated.
Bump of immer coming soon, at least if it's smooth^^

**Comment by cyrilRomain** [comment]
Immer bumped.
Build successfully locally w/o any changes. Let's see if travis is happy too.

**Comment by cyrilRomain** [comment]
Added zug required dependency.

**Comment by arximboldi** [comment]
For the `zug` addition to really work, it needs to be mentioned in `default.nix` and `shell.nix`. Thank you a lot for taking care of this!

**Comment by cyrilRomain** [comment]
Done. Thank you for your hints! ;)

**Comment by cyrilRomain** [comment]
Added zug in lager dependencies.
Should be OK now.

**Comment by cyrilRomain** [comment]
Damn.
For the first error, I'm wondering if `lager::identity` should be only used in the else statement of EWIG_ENABLE_DEBUGGER, as in the autopong lager example, or if it can be composed with the `with_debugger` as in the ncurses lager example.

For the second (subsequent?) error, FYI I removed the `LAGER_STRUCT(std, monostate);` from main.cpp otherwise I get: 
`error: ambiguous overload for ‘operator==’ (operand types are ‘const std::monostate’ `
Also the lager debugger already includes `lager/extra/cereal/variant_with_name.hpp` which now define serialization for monostate. Do you have a clue on this ?
(FYI I use boost 1.78)

**Comment by arximboldi** [comment]
Sorry @cyrilRomain for the long silence, those issues were non trivial so I needed to take a deeper look. I've fixed the issues in #22. Thank you so much for your contribution!

**Pull request closed without merging**
