### PR TITLE
Make it work with newer nixpkgs

### PR DESCRIPTION
**Pull request by BBBSnowball**
- `stdenv.lib` is gone, just use `lib` (from `nixpkgs`)
- `gcc5` is gone, `gcc49` and `gcc6` don't work (missing symbols while linking ewig) -> use `gcc7` and update `libhttpserver` to 0.16.0

This is my first time using ewig ([great talk!](https://www.youtube.com/watch?v=sPhpelUfu8Q)) so I don't know how to properly test it. ewig starts and displays a file so I guess it can't be all bad. In addition, `ewig-debug` does open a webserver and it delivers its main page (but I don't have any browser with Javascript on that machine).

### CODE REVIEW

**Comment by BBBSnowball** [comment]
I think, that CI pipeline might be broken - by other changes to `nix` :-D

```
Error: Unable to process command '::add-path::/nix/var/nix/profiles/per-user/runner/profile/bin' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

**Comment by arximboldi** [comment]
Yes, the Nix related actions need to be upgraded to their latest versions. Sorry about that!

**Comment by BBBSnowball** [comment]
No problem at all!

Is there anything I can do to help? Maybe bumping cachix/install-nix-action@v11 to v16 will help (although I don't see anything obvious in the release notes).

Edit: Ok, Github is smart enough to not let me modify the workflow. It would be kind of scary if I could just do this.

**Comment by arximboldi** [comment]
Thanks a lot! Yes, that's what I had in mind. I think `cachix-action` may need an upgrade too.

**Review by arximboldi — APPROVED** [review]
Thank you so much!

**Pull request merged**
