### PR TITLE
Changed curses to use standard paths and cmake

### PR DESCRIPTION
**Pull request by dunkyp**
Couldn't build the code on arch linux initially. So patched the code to not use the nonstandard ncursesw/ncurses.h path.

### CODE REVIEW

**Comment by arximboldi** [comment]
Hey! Thanks a lot for the contribution. I am unsure about this one because I think one needs `ncursesw` for UTF-8 to work properly...

**Comment by dunkyp** [comment]
Indeed. I've had some trouble compiling this for macos as well. I've updated the cmake file as per https://gitlab.kitware.com/cmake/cmake/commit/4b02afc0caf46244f12f87f363ace6c1ab47fae5. The relevant symbols are declared in "curses.h" (if it's compiled with the wide character support and ncurses.h is generally just a symlink). However some systems (for example arch don't ues the ncursesw) folder in /usr/include.

**Comment by dunkyp** [comment]
I'll try and fix the ncurses support for macos soon!

**Review by arximboldi — COMMENTED** [review]
LGTM :+1:

**Review by arximboldi — APPROVED** [review]

**Pull request merged**
